# Минимальный ClickHouse для Sentry v29 (внешний ClickHouse обязателен)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: sentry
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: sentry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.3
          env:
            - name: CLICKHOUSE_PASSWORD
              value: "clickhouse"
          ports:
            - containerPort: 9000
              name: native
            - containerPort: 8123
              name: http
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: clickhouse-data
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: sentry
spec:
  selector:
    app: clickhouse
  ports:
    - port: 9000
      targetPort: 9000
      name: native
    - port: 8123
      targetPort: 8123
      name: http
